name: notify-on-label-change

on:
  pull_request:
    types: [labeled]

jobs:
  notify_telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR target branch
        run: |
          base_branch="${{ github.event.pull_request.base.ref }}"
          if [ "$base_branch" = "master" ]; then
            echo "check_for_label=true" >> "$GITHUB_ENV"
          else
            echo "check_for_label=false" >> "$GITHUB_ENV"
          fi

      - name: Check for 'Ready for review' label
        if: env.check_for_label == 'true'
        run: |
          if [[ "${{ github.event.label.name }}" == "Ready for review" ]]; then
            echo "send_telegram=true" >> "$GITHUB_ENV"
          else
            echo "send_telegram=false" >> "$GITHUB_ENV"
          fi

      - name: Telegram Message Notify
        if: env.send_telegram == 'true'
        run: |
          echo "Sending Telegram message..."
          echo "@kushal2601" > message.txt
          echo "PR: ${{ github.event.pull_request.title }}" >> message.txt
          echo "Author: ${{ github.event.pull_request.user.login }}" >> message.txt
          echo "URL: ${{ github.event.pull_request.html_url }}" >> message.txt
          cat message.txt
          TELEGRAM_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_TO=${{ secrets.TELEGRAM_CHAT_ID }}
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage -d chat_id=$TELEGRAM_TO -d text="$(cat message.txt)"
